baseURL = "https://www.lambda-out-loud.com/"
languageCode = "en-us"
title = "Lambda Out Loud"
theme = "arabica"

[paginator]
  paginate = 5

[taxonomies]
  category = "categories"
  tag = "tags"
  grimoire = "grimoire"

[params]
    description = "A blog about all things code"
    mainSections = ["posts", "creative-code"]

[menu]
    [[menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts/"
        weight = -20

    [[menu.main]]
        identifier = "grimoire"
        name = "Grimoire"
        url = "/grimoire/"
        weight = -5

    [[menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags/"
        weight = -5

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "friendly"
    tabWidth = 4
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
